# tests/test_api.py
import os
import json
import requests

# Allow CI (or local) to override the port via env var; default to 8000
PORT = os.getenv("MODEL_PORT", "8000")
BASE_URL = f"http://127.0.0.1:{PORT}"
URL = f"{BASE_URL}/invocations"

def test_api_records():
    # Load the payload generated by scripts/generate_payload.py
    with open("payload_records.json") as f:
        records = json.load(f)

    # Wrap under the required key for MLflow pyfunc
    payload = {"dataframe_records": records}

    resp = requests.post(URL, json=payload)
    assert resp.status_code == 200, (
        f"Unexpected status {resp.status_code}: {resp.text}"
    )

    preds = resp.json().get("predictions", resp.json())
    print("API returned:", preds)
    assert isinstance(preds, list)
